[build]
  command = "npm run build:frontend"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://spicepop-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 