[build]
  command = "npm run build:frontend"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "/api"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://spicepop-backend.onrender.com;"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/*"
  to = "https://spicepop-backend.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 