[build]
  command = "rm -rf dist && npm install --include=dev && npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[dev]
  command = "npm run dev:frontend"
  port = 5173
  targetPort = 5173
  publish = "dist/public"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

# API redirects must come first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# SPA fallback must come last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
