services:
  - type: web
    name: spicepop-backend
    env: node
    region: ohio
    plan: free
    buildCommand: |
      npm install --omit=dev
      npm run build:server
    startCommand: NODE_ENV=production node dist/server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://spicepop.netlify.app 