services:
  - type: web
    name: spicepop-backend
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build:server
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://spicepopp.netlify.app
    autoDeploy: true 